Bid/urls.py
from rest_framework.urlpatterns import format_suffix_patterns
from django.urls import path
from Bid.views import *

app_name = 'Bid'

urlpatterns = [

    path('bidlist', BidListView.as_view({'get':'list','post':'create'})),

    path('bid/<str:bid_number>', BidUpdateView.as_view()),

    path('bid-row/delete/<int:id>', BidDeleteView.as_view({'delete':'destroy'})),

    path('bid/send/<str:bid_number>', BidSendView.as_view()),

    path('bid/set-to-won/<str:bid_number>', BidSettoWonView.as_view()),
    
    path('bid/status/cancel/<str:bid_number>', BidSettoCancelView.as_view()),

]

urlpatterns = format_suffix_patterns(urlpatterns)

Invoice/urls.py
from rest_framework.urlpatterns import format_suffix_patterns
from django.urls import path
from Invoice import views

urlpatterns = [

    path('invoice', views.InvoiceList.as_view()),

    path('invoice/create', views.CreateInvoice.as_view()),

    path('invoice/number/get', views.GetInvoiceNumber.as_view()),

    path('invoice/customer/<int:cust_org_id>', views.CustomerOrganizationReconciledProjectView.as_view()),

    path('invoice/project-group-list', views.ProjectGroupInvoiceList.as_view()),

    path('invoice/<str:invoice_number>/status', views.InvoiceUpdateStatusView.as_view()),

    path('invoice/<str:invoice_number>/edit', views.InvoiceUpdateView.as_view()),

    path('invoice-row/create', views.InvoiceRowView.as_view()),
    
    path('invoice-row/<int:invoice_row_id>/edit', views.InvoiceRowUpdateView.as_view()),

    path('invoice/<str:invoice_number>/pdf', views.InvoicePdfView.as_view()),
    path('invoicehtml', views.invoiceHTML.as_view()),

    # Multiple Invoice Data Download In Single PDF 
    path('multiple-invoice-data/pdf', views.MulitpleInvoiceInSinglePdfDownload.as_view()),

    # Send Email Invoice PDF
    path('invoice/send-email', views.SendInvoicePdfEmailView.as_view()),

    # Download All Invoice CSV
    path('invoice/invoice-xls-download', views.InvoiceListXLSDownload.as_view()),

    # Download Invoice Row XLSX
    path('invoice/invoicerow-xlsx-download', views.InvoiceRowsXLSXDownload.as_view()),

    # Download Invoice Data By Project
    path('invoice/invoice-byproject-xlsx', views.InvoiceByProjectXLSX.as_view()),


    # DRAFTINVOICE AND DRAFTINVOICEROW APIS
    path('draftinvoice-rows/multiple/create', views.DraftInvoiceAndRowsCreate.as_view()),

    path('draft-invoice-list', views.DraftInvoiceListView.as_view()),

    path('draft-invoice-status-update', views.DraftInvoiceStatusUpdateView.as_view()),

    path('draft-invoice-row-list', views.DraftInvoiceRowsListView.as_view()),

    path('draft-invoice-update/file-upload/<int:pk>', views.DraftInvoiceUpdateFileUploadView.as_view()),

    path('draft-invoice/get-counts', views.DraftInvoiceGetCounts.as_view()),

    path('draft-invoice-list-stats/approved-status', views.ListDraftInvoiceStatsApprovedStatus.as_view()),

    path('draft-invoice-row-list-by-project', views.DraftInvoiceRowsListByProjectView.as_view()),

    path('draft-invoice-row-delete', views.DraftInvoiceRowsDeleteAPI.as_view()),

    #INVOICE PAYEMNT REMINDER EMAIL SENDING & CREATING TABLE DATA IN THIS API
    path('invoice/payment-reminder/email', views.InvoicePaymentReminderEmailView.as_view()),

    path('invoice-po-wise/payment-reminder/email', views.InvoiceListPaymentReminderEmailView.as_view()),

    path('invoice/<int:invoice_id>/delete', views.InvoiceDeleteView.as_view()),

    path('invoice/receivable-amount/<str:customer_id>', views.TotalOverDueReceivablesView.as_view()),

    path('invoice/payable-amount/<str:customer_id>', views.TotalOverDuePayablesView.as_view()),

    path('invoice-revert/<str:invoice_number>', views.InvoiceRevertApi.as_view()),

    path('invoice/due-date-reminder', views.CustomerInvoiceDueDateReminderList.as_view()),
    
    path('customer-reminder-invoice-list/<str:customer_id>/<str:invoice_currency_id>', views.CustomerWiseInvoiceDueDateList.as_view()),
    
    path('invoice/companyupdate', views.InvoiceCompanyUpdate.as_view()),

    path('draft-invoice-revert/<int:project_id>/<int:draftinvoice_id>', views.DraftInvoiceRevert.as_view()),
    
    path('invoice/month-wise-email-sent', views.InvoiceListSendEmailMonthWiseAPI.as_view()),

    path('invoice/draft-invoice-notes/<int:draft_invoice_id>', views.DraftInvoiceNotesAPI.as_view()),

]

urlpatterns = format_suffix_patterns(urlpatterns)

myproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from Surveyentry.views import healtcheck

urlpatterns = [

    path('',healtcheck.as_view()), ## Warning!..Don't Delete This API ##

    # Django admin urls
    path('admin/', admin.site.urls),

    # initial-setup app urls
    path(settings.APP_PATH, include('InitialSetup.urls')),

    # employee app urls
    path(settings.APP_PATH, include('employee.urls')),

    # bid app urls
    path(settings.APP_PATH, include('Bid.urls')),

    # Customer app urls
    path(settings.APP_PATH, include('Customer.urls')),

    # Supplier app urls
    path(settings.APP_PATH, include('Supplier.urls')),

    # Project app urls
    path(settings.APP_PATH, include('Project.urls')),

    # Data Download app urls
    path(settings.APP_PATH, include('DataDownload.urls')),

    # Questions app urls
    path(settings.APP_PATH, include('Questions.urls')),

    # Prescreener app urls
    path(settings.APP_PATH, include('Prescreener.urls')),

    # Reconciliation app urls
    path(settings.APP_PATH, include('reconciliation.urls')),

    # TolunaClientAPI app urls
    path(settings.APP_PATH, include('ClientSupplierAPIIntegration.TolunaClientAPI.urls')),

    # ZampliaClientAPI app urls
    path(settings.APP_PATH, include('ClientSupplierAPIIntegration.ZampliaClientAPI.urls')),

    # Surveyentry app urls
    path('v2/', include('Surveyentry.urls')),

    # Landing Page app urls
    path('', include('Landingpage.urls')),

    # Invoice app urls
    path(settings.APP_PATH, include('Invoice.urls')),
    
    # Supplier Dashboard urls
    path(settings.APP_PATH, include('supplierdashboard.urls')),

    # AffiliateRouter app urls
    path(f'{settings.APP_PATH}affiliaterouter/', include('affiliaterouter.urls')),
    
    # SupllierAPI app urls
    path(settings.APP_PATH, include('SupplierAPI.urls')),
    
    # SupplierRouter app urls
    path(settings.APP_PATH, include('SupplierRouter.urls')),
    
    # SupplierRouter app urls
    path(settings.APP_PATH, include('Report_section.urls')),

    # Recontact_Section app urls
    path(settings.APP_PATH, include('Recontact_Section.urls')),

    # Supplier Final IDS Email urls
    path(settings.APP_PATH, include('Supplier_Final_Ids_Email.urls')),

    # Question Mapping SupplierAPI urls
    path(settings.APP_PATH, include('QuestionSupplierAPI.urls')),
    
    # Question Mapping scrubsupplierids urls
    path(settings.APP_PATH, include('scrubsupplierids.urls')),
    
    # Admin Dashboard urls
    path(settings.APP_PATH, include('AdminDashboard.urls')),

    # Supplier Invoice urls
    path(settings.APP_PATH, include('SupplierInvoice.urls')),

    # SupplierBuyerAPI urls
    path('', include('SupplierBuyerAPI.urls')),
    
    # Supplier Invite On Project urls
    path(settings.APP_PATH, include('SupplierInviteOnProject.urls')),
    
    # Company Bank Details urls
    path(settings.APP_PATH, include('CompanyBankDetails.urls')),

    # Client Supplier Invoice Payment urls
    path(settings.APP_PATH, include('ClientSupplierInvoicePayment.urls')),

    # Panel Integration urls
    path(settings.APP_PATH, include('PanelIntegration.urls')),

    # Sales_CommissionViewSet
    path(settings.APP_PATH, include('Sales_Commission.urls')),

    # AD Panel Dashboard urls
    path(settings.APP_PATH, include('Ad_Panel_Dashboard.urls')),

    # Email Template App Urls
    path(settings.APP_PATH, include('email_template_app.urls')),

    # Notifications App Urls
    path(settings.APP_PATH, include('Notifications.urls')),
    
    # Backup App Urls
    path(settings.APP_PATH, include('backup.urls')),
    
    path('', include('AutomationAPI.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATICFILES_DIRS)

Invoice/models.py
from django.db import models
from django.db.models.fields.related import ForeignKey
from Project.models import *
from Customer.models import *
from employee.models import *


class Invoice(models.Model):

    status = (
        ('1', 'Draft'),
        ('2', 'Sent'),
        ('3', 'Paid'),
        ('4', 'Cancel'),
    )
    tax_choices = (
        ('1', 'None'),
        ('2', 'IGST'),
        ('3', 'SGST/CGST'),
    )

    invoice_number = models.CharField(max_length=50, default="")
    prefix = models.CharField(max_length=50, default="")
    suffix = models.IntegerField(null=True, blank=True)
    invoice_project = models.ManyToManyField(Project)
    invoice_description = models.TextField(null=True, blank=True)
    invoice_po_number = models.TextField(null=True, blank=True) # Keeping it just like that, Not using this Field at all
    invoice_customer = models.ForeignKey(CustomerOrganization, on_delete=models.CASCADE)
    invoice_contact = models.ForeignKey(ClientContact, on_delete=models.CASCADE)
    invoice_status = models.CharField(max_length=1, choices=status, default='1')
    invoice_show_conversion_rate = models.BooleanField(default=False)
    invoice_conversion_rate = models.FloatField(default=0)
    invoice_total_amount_in_USD = models.FloatField(default=0)
    invoice_total_amount = models.FloatField(default=0)
    invoice_subtotal_amount = models.FloatField(default=0)


    # Additional Fields
    invoice_date = models.DateField()
    invoice_due_date = models.DateField()
    invoice_ship_to_address_enable = models.BooleanField(default=True)
    invoice_tax = models.CharField(max_length=1, choices=tax_choices, default='1')
    invoice_IGST_value = models.FloatField(default=0)
    invoice_SGST_value = models.FloatField(default=0)
    invoice_CGST_value = models.FloatField(default=0)
    invoice_TDS_amount = models.FloatField(default=0)
    discount = models.FloatField(default=0)
    subtotal_after_discount = models.FloatField(default=0)
    invoice_TDS_percentage = models.FloatField(default=0)
    invoice_show_stamp = models.BooleanField(default=False)
    invoice_currency = models.ForeignKey(Currency, on_delete=models.SET_NULL, null=True, blank=True)

    # Company Invoice Bank Detail
    company_invoice_bank_detail = models.ForeignKey('CompanyBankDetails.CompanyInvoiceBankDetail', null=True, blank=True, default="", on_delete=models.SET_NULL)

    # Common relation Fields
    created_by = models.ForeignKey(
        EmployeeProfile, on_delete=models.SET_NULL, null=True, related_name='invoice_created_by')
    modified_by = models.ForeignKey(
        EmployeeProfile, on_delete=models.SET_NULL, null=True, related_name='invoice_modified_by')
    created_at = models.DateTimeField(auto_now_add=True, editable=False)
    modified_at = models.DateTimeField(auto_now=True)
    
    def get_invoice_contact_full_name(self):
        return f'{self.invoice_contact.client_firstname} {self.invoice_contact.client_lastname}'

    class Meta:
        ordering = ('-id',)
    
    def __str__(self):
        return '{}'.format(self.invoice_number)


class InvoiceRow(models.Model):

    invoice = models.ForeignKey(Invoice, on_delete=models.CASCADE)
    project_group_number = models.ForeignKey(ProjectGroup, on_delete=models.SET_NULL, null=True) # Keeping it just like that, Not using this Field at all
    row_project_number = models.ForeignKey(Project, on_delete=models.CASCADE, null=True)
    row_po_number = models.TextField(default='',blank=True)
    row_hsn_code = models.CharField(max_length=200, null=True)
    row_name = models.CharField(max_length=255, null=False)
    row_completes = models.IntegerField(default=0)
    row_cpi = models.FloatField(default=0)
    row_total_amount = models.FloatField(default=0)
    row_description = models.TextField(null=True, default="")

    # Common relation Fields
    created_by = models.ForeignKey(
        EmployeeProfile, on_delete=models.SET_NULL, null=True, related_name='invoice_row_created_by')
    modified_by = models.ForeignKey(
        EmployeeProfile, on_delete=models.SET_NULL, null=True, related_name='invoice_row_modified_by')
    created_at = models.DateTimeField(auto_now_add=True, editable=False)
    modified_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('id',)


class DraftInvoice(models.Model):

    cpi_calculation = (
        ('1', 'Including GST'),
        ('2', 'Excluding GST'),
    )

    project = models.OneToOneField(Project, null=True, on_delete=models.CASCADE)
    invoice_to_customer = models.ForeignKey(CustomerOrganization, null=True, on_delete=models.CASCADE)
    invoice_currency = models.ForeignKey(Currency, null=True, on_delete=models.CASCADE)
    bid_currency = models.ForeignKey(Currency, null=True, on_delete=models.CASCADE, related_name='draft_invoice_bid_currency')
    confirm_email_file = models.FileField(upload_to='invoice_confirmation_attachment/', max_length=5000, null=True, blank=True)
    invoice_total = models.FloatField(null=True, blank=True)
    bid_total = models.FloatField(null=True, blank=True)
    conversion_rate = models.FloatField(null=True, blank=True)
    cpi_calculation_method = models.CharField(null=True, blank=True, choices=cpi_calculation, max_length=1)
    draft_approved = models.BooleanField(default=False)
    approval_note = models.TextField(null=True, blank=True)
    notes_from_pm = models.TextField(null=True, blank=True)
    project_invoiced_date = models.DateField(null=True)

    BA_approved = models.BooleanField(default=False)
    Accountant_approved = models.BooleanField(default=False)

    BA_approved_by = models.ForeignKey(
        EmployeeProfile, on_delete=models.SET_NULL, null=True, related_name='draft_invoice_ba_approved_by')

    # Common relation Fields
    created_by = models.ForeignKey(
        EmployeeProfile, on_delete=models.SET_NULL, null=True, related_name='draft_invoice_created_by')
    modified_by = models.ForeignKey(
        EmployeeProfile, on_delete=models.SET_NULL, null=True, related_name='draft_invoice_modified_by')
    created_at = models.DateTimeField(auto_now_add=True, editable=False)
    modified_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('id',)



class DraftInvoiceRow(models.Model):
    draft_invoice = models.ForeignKey(DraftInvoice, null=True, on_delete=models.CASCADE)
    po_number = models.CharField(max_length=100, null=True, blank=True)
    description = models.CharField(max_length=255, null=True, blank=True)
    bid_cpi = models.FloatField(default=0)
    cpi = models.FloatField(default=0)
    completes = models.IntegerField(default=0)
    total = models.FloatField(default=0)
    bid_total = models.FloatField(default=0)

    class Meta:
        ordering = ('id',)


class InvoicePaymentReminderEmail(models.Model):
    invoices = models.ManyToManyField(Invoice)
    customer = models.ForeignKey(CustomerOrganization,on_delete=models.SET_NULL, null=True, blank=True)
    reminder_date = models.DateField(auto_now_add=True)
    added_by = models.ForeignKey(
        EmployeeProfile, on_delete=models.SET_NULL, null=True, related_name='invoice_payment_reminder_email')



class DraftInvoiceChangesStore(models.Model):
    draft_invoice = models.ForeignKey(DraftInvoice, null=True, on_delete=models.CASCADE)
    approved_date = models.DateTimeField(null=True)
    approved_by = models.ForeignKey(EmployeeProfile, on_delete=models.SET_NULL, null=True, related_name='draft_invoice_create_update_approved_approved_by')
    payload_data = models.JSONField(max_length=10000, null = True)

    # Common relation Fields
    created_by = models.ForeignKey(EmployeeProfile, on_delete=models.SET_NULL, null=True, related_name='draft_invoice_create_update_approved_created_by')

    created_at = models.DateTimeField(auto_now_add=True, editable=False)
    modified_at = models.DateTimeField(auto_now=True)



class DraftInvoiceNotes(models.Model):
    draft_invoice = models.ForeignKey(DraftInvoice, null=True, on_delete=models.CASCADE)
    notes = models.TextField(null=True, blank=True)

    # Common relation Fields
    created_by = models.ForeignKey(EmployeeProfile, on_delete=models.SET_NULL, null=True, related_name='draft_invoice_notes_created_by')

    created_at = models.DateTimeField(auto_now_add=True, editable=False)
    modified_at = models.DateTimeField(auto_now=True)

templates/Invoice/invoice_month_wise_email_send.html
<!DOCTYPE html
	PUBLIC "-//W3C//DTD XHTML 1.0 Transitional //EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xmlns:o="urn:schemas-microsoft-com:office:office"
	xmlns:v="urn:schemas-microsoft-com:vml">

<head>
	<!--[if gte mso 9]><xml><o:OfficeDocumentSettings><o:AllowPNG/><o:PixelsPerInch>96</o:PixelsPerInch></o:OfficeDocumentSettings></xml><![endif]-->
	<meta content="text/html; charset=utf-8" http-equiv="Content-Type" />
	<meta content="width=device-width" name="viewport" />
	<!--[if !mso]><!-->
	<meta content="IE=edge" http-equiv="X-UA-Compatible" />
	<!--<![endif]-->
	<title></title>
	<!--[if !mso]><!-->
	<!--<![endif]-->
	<style type="text/css">
		body {
			margin: 20;
			padding: 20;
		}

		table,
		th,
		td,
		tr {
			vertical-align: top;
			border: 1px solid black;;
			border-collapse: collapse;
		}

		* {
			line-height: inherit;
		}

		a[x-apple-data-detectors=true] {
			color: inherit !important;
			text-decoration: none !important;
		}
	</style>
	<style id="media-query" type="text/css">
		
	</style>
	<style id="icon-media-query" type="text/css">
		
		</style>
</head>

<body class="clean-body" style="margin: 0; padding: 0; background-color: #FFFFFF;">
	
	<div>
		<p>
			Hi Team,<br>
		</p>
		<p>
			I hope this email finds you well. I am writing to provide you with the invoice report for the month of June 2024.<br>
            Kindly review the below details and let me know if you have any questions or require further clarification.<br>

		</p>
		<p>
            Please take the time to carefully examine the provided invoices. Should you come across any discrepancies or have any <br>
            queries regarding specific items, amounts, or other details, kindly reach out to me directly. I will be more than happy to <br>
            address any concerns you may have and provide any necessary explanations or documentation.

		</p>
		<p>
			Here are the lists..<br>
		</p>
	</div>



	<table style="text-align: center; margin-block: 20px;" width="60%">
		<thead>
			<!-- <tr>
				<th colspan="5" style="color:#555555;direction:ltr;font-family:Arial, Helvetica Neue, Helvetica, sans-serif;padding-bottom: 0px; padding-top: 0px;">
					<h1 style="margin-bottom: 0px; margin-top: 0px;">Supplier Final IDs</h1>
				</th>
			</tr> -->
			<tr>
					<th>Invoice Number</th>
					<th>Invoice Date</th>
					<th>Invoice Due Date</th>
					<th>Invoice Total Amount</th>
				
			</tr>
		</thead>
		<tbody>
				{% for invoice in invoice_list %}
				<tr>
					<td>{{invoice.invoice_number}}</td>
					<td>{{invoice.invoice_date}}</td>
					<td>{{invoice.invoice_due_date}}</td>
					<td>{{invoice.invoice_currency.currency_iso}} {{invoice.invoice_total_amount}}</td>
				</tr>
				{% endfor %}
		</tbody>
	</table>
	
		<!-- <div style="height: 0.8cm;width: 10%;border-color: black;border-width: 1px;border-style: none double double;text-align: center; margin-left: 19%;">
		</div> -->

		<br>
		<br>
		Thank you,
		<br>
		Accounts Team


</body>

</html>

templates/Invoice/invoice_payment_reminder_email.html
<!DOCTYPE html
	PUBLIC "-//W3C//DTD XHTML 1.0 Transitional //EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xmlns:o="urn:schemas-microsoft-com:office:office"
	xmlns:v="urn:schemas-microsoft-com:vml">

<head>
	<!--[if gte mso 9]><xml><o:OfficeDocumentSettings><o:AllowPNG/><o:PixelsPerInch>96</o:PixelsPerInch></o:OfficeDocumentSettings></xml><![endif]-->
	<meta content="text/html; charset=utf-8" http-equiv="Content-Type" />
	<meta content="width=device-width" name="viewport" />
	<!--[if !mso]><!-->
	<meta content="IE=edge" http-equiv="X-UA-Compatible" />
	<!--<![endif]-->
	<title></title>
	<!--[if !mso]><!-->
	<!--<![endif]-->
	<style type="text/css">
		body {
			margin: 20;
			padding: 20;
		}

		table,
		th,
		td,
		tr {
			vertical-align: top;
			border: 1px solid black;;
			border-collapse: collapse;
		}

		* {
			line-height: inherit;
		}

		a[x-apple-data-detectors=true] {
			color: inherit !important;
			text-decoration: none !important;
		}
	</style>
	<style id="media-query" type="text/css">
		/* @media (max-width: 520px) {

			.block-grid,
			.col {
				min-width: 320px !important;
				max-width: 100% !important;
				display: block !important;
			}

			.block-grid {
				width: 100% !important;
			}

			.col {
				width: 100% !important;
			}

			.col_cont {
				margin: 0 auto;
			}

			img.fullwidth,
			img.fullwidthOnMobile {
				max-width: 100% !important;
			}

			.no-stack .col {
				min-width: 0 !important;
				display: table-cell !important;
			}

			.no-stack.two-up .col {
				width: 50% !important;
			}

			.no-stack .col.num2 {
				width: 16.6% !important;
			}

			.no-stack .col.num3 {
				width: 25% !important;
			}

			.no-stack .col.num4 {
				width: 33% !important;
			}

			.no-stack .col.num5 {
				width: 41.6% !important;
			}

			.no-stack .col.num6 {
				width: 50% !important;
			}

			.no-stack .col.num7 {
				width: 58.3% !important;
			}

			.no-stack .col.num8 {
				width: 66.6% !important;
			}

			.no-stack .col.num9 {
				width: 75% !important;
			}

			.no-stack .col.num10 {
				width: 83.3% !important;
			}

			.video-block {
				max-width: none !important;
			}

			.mobile_hide {
				min-height: 0px;
				max-height: 0px;
				max-width: 0px;
				display: none;
				overflow: hidden;
				font-size: 0px;
			}

			.desktop_hide {
				display: block !important;
				max-height: none !important;
			}
		} */
	</style>
	<style id="icon-media-query" type="text/css">
		/* @media (max-width: 520px) {
			.icons-inner {
				text-align: center;
			}

			.icons-inner td {
				margin: 0 auto;
			}
		}
		@media (min-width: 1200px){
			.container, .container-lg, .container-md, .container-sm, .container-xl {
				max-width: 1140px;
			}
		} */
		</style>
</head>

<body class="clean-body" style="margin: 0; padding: 0; background-color: #FFFFFF;">
	
	<div>
		<p>
			Hi Team,<br>
		</p>
		<p>
			Just wanted to follow-up on the payment status of all of our overdue and upcoming dues invoices. Could you please share the status and expected date of payment?<br>
		</p>
		<p>
			Please find the list of all invoices below and you can find the PO# associated with each invoice in the attachment.<br>
		</p>
	</div>



	<table style="text-align: center; margin-block: 20px;" width="60%">
		<thead>
			<!-- <tr>
				<th colspan="5" style="color:#555555;direction:ltr;font-family:Arial, Helvetica Neue, Helvetica, sans-serif;padding-bottom: 0px; padding-top: 0px;">
					<h1 style="margin-bottom: 0px; margin-top: 0px;">Supplier Final IDs</h1>
				</th>
			</tr> -->
			<tr>
				{% if invoice_list %}
					<th>Invoice Number</th>
					<th>Invoice Amount</th>
					<th>Invoice Date</th>
					<th>Due Date</th>
					<th>Due By (Days)</th>
				{% else %}
					<th>Invoice Number</th>
					<th>Invoice PO Number</th>
					<th>Invoice Amount</th>
					<th>Invoice Date</th>
					<th>Due Date</th>
					<th>Due By (Days)</th>
				{% endif %}
				
			</tr>
		</thead>
		<tbody>
			{% if invoice_list %}
				{% for invoice in invoice_list %}
				<tr>
					<td>{{invoice.invoice_number}}</td>
					<td>{{invoice.invoice_currency.currency_iso}} {{invoice.invoice_total_amount}}</td>
					<td>{{invoice.invoice_date}}</td>
					<td>{{invoice.invoice_due_date}}</td>
					<td>{{invoice.due_days.days}}</td>
				</tr>
				{% endfor %}
			{% else %}
				{% for invoice_row in invoice_row_qs %}
				<tr>
					<td>{{invoice_row.invoice.invoice_number}}</td>
					<td>{{invoice_row.row_po_number}}</td>
					<td>{{invoice_row.invoice.invoice_currency.currency_iso}} {{invoice_row.row_total_amount}}</td>
					<td>{{invoice_row.invoice.invoice_date}}</td>
					<td>{{invoice_row.invoice.invoice_due_date}}</td>
					<td>{{invoice_row.due_days.days}}</td>
				</tr>
				{% endfor %}
			{% endif %}
		</tbody>
	</table>
	
		<!-- <div style="height: 0.8cm;width: 10%;border-color: black;border-width: 1px;border-style: none double double;text-align: center; margin-left: 19%;">
		</div> -->

		<br>
		<br>
		Thank you,
		<br>
		Accounts Team


</body>

</html>

templates/Invoice/project_status_reconciled_invoice_rejected.html
<!DOCTYPE html
	PUBLIC "-//W3C//DTD XHTML 1.0 Transitional //EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xmlns:o="urn:schemas-microsoft-com:office:office"
	xmlns:v="urn:schemas-microsoft-com:vml">

<head>
	<!--[if gte mso 9]><xml><o:OfficeDocumentSettings><o:AllowPNG/><o:PixelsPerInch>96</o:PixelsPerInch></o:OfficeDocumentSettings></xml><![endif]-->
	<meta content="text/html; charset=utf-8" http-equiv="Content-Type" />
	<meta content="width=device-width" name="viewport" />
	<!--[if !mso]><!-->
	<meta content="IE=edge" http-equiv="X-UA-Compatible" />
	<!--<![endif]-->
	<title></title>
	<!--[if !mso]><!-->
	<!--<![endif]-->
	<style type="text/css">
		body {
			margin: 0;
			padding: 0;
		}

		table,
		th,
		td,
		tr {
			vertical-align: top;
			border: 1px solid black;;
			border-collapse: collapse;
		}

		* {
			line-height: inherit;
		}

		a[x-apple-data-detectors=true] {
			color: inherit !important;
			text-decoration: none !important;
		}
	</style>
	
</head>

<body class="clean-body" style="margin: 0; padding: 0; background-color: #FFFFFF;">
	
	<div>
		<p>
			Hi {{project.project_manager.first_name}} {{project.project_manager.last_name}},
		</p>
		<p>
			Project Invoice for Project number {{project.project_number}} has been rejected by {{request.user.first_name}} {{request.user.last_name}} due to following reason:
            <br>
            <br>
            {{project.draftinvoice.approval_note}}
		</p>
	</div>

		<br>
		Thanks,
		<br>
		Accounts Team


</body>

</html>